[package]
name = "raytrace"
version = "0.1.0"
authors = ["Sebastian Paarmann <sebastian.paarmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.7"
rand = "0.7.3"
